### ISSUE TITLE
Problems using Tensorboard

### ISSUE THREAD

**Issue by NMesaC** [NMesaC/Tensorflow-and-Tensorboard-Problems-Raspberry-Pi#1]
Hello! I am new to utilizing tensorflow and tensorboard. I recently compiled tensorflow from pip onto a Raspberry Pi 3B and was using a book to get a hang of tensorflow. However, after trying to see if some example code would run, I was given an error code that didn't make sense after running a linux command. The Python Code would run, but the linux command gives and error message. After researching a bit, I haven't come up with a solution, so any help would be appreciated! The example code and error message are below.

(I am new to github, so please excuse that. The bold error message is where I think the problems are but I'm not sure)

`input_value = tf.constant(0.5,name="input_value")
weight = tf.Variable(1.0,name="weight")
expected_output = tf.constant(0.0,name="expected_output")
model = tf.multiply(input_value,weight,"model")loss_function =
tf.pow(expected_output - model,2,name="loss_function")
optimizer =
tf.train.GradientDescentOptimizer(0.025).minimize(loss_function)
for value in [input_value,weight,expected_output,model,loss_function]:
tf.summary.scalar(value.op.name,value)
summaries = tf.summary.merge_all()sess = tf.Session()
summary_writer = tf.summary.FileWriter('log_simple_stats',sess.graph)
sess.run(tf.global_variables_initializer())
for i in range(100):
summary_writer.add_summary(sess.run(summaries),i)
sess.run(optimizer)` 
(This code is run in Python, but the linux command produces this error)

`tensorboard --logdir = log_simple_stats  (The linux command causing issues)
**2018-06-13 01:23:17.213927: W tensorflow/core/lib/png/png_io.cc:87] PNG warning: Application built with libpng-1.2.50 but running with 1.6.34**
Traceback (most recent call last):
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid PNG header, data size 3331
	 [[Node: DecodePng = DecodePng[channels=0, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_0_0)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/tensorflow/bin/tensorboard", line 11, in <module>
    sys.exit(run_main())
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/main.py", line 36, in run_main
    tf.app.run(main)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/main.py", line 45, in main
    default.get_assets_zip_provider())
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/program.py", line 166, in main
    tb = create_tb_app(plugins, assets_zip_provider)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/program.py", line 201, in create_tb_app
    flags=FLAGS)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/backend/application.py", line 126, in standard_tensorboard_wsgi
    plugin_instances = [constructor(context) for constructor in plugins]
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/backend/application.py", line 126, in <listcomp>
    plugin_instances = [constructor(context) for constructor in plugins]
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/plugins/beholder/beholder_plugin.py", line 47, in __init__
    self.most_recent_frame = im_util.get_image_relative_to_script('no-data.png')
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/plugins/beholder/im_util.py", line 254, in get_image_relative_to_script
    return read_image(filename)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/plugins/beholder/im_util.py", line 242, in read_image
    return np.array(decode_png(image_file.read()))
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/plugins/beholder/im_util.py", line 161, in __call__
    return self.run(*args, **kwargs)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/plugins/beholder/im_util.py", line 180, in run
    self._image_placeholder: image,
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 710, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 5180, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid PNG header, data size 3331
	 [[Node: DecodePng = DecodePng[channels=0, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_0_0)]]

Caused by op 'DecodePng', defined at:
  File "/home/pi/tensorflow/bin/tensorboard", line 11, in <module>
    sys.exit(run_main())
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/main.py", line 36, in run_main
    tf.app.run(main)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/main.py", line 45, in main
    default.get_assets_zip_provider())
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/program.py", line 166, in main
    tb = create_tb_app(plugins, assets_zip_provider)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/program.py", line 201, in create_tb_app
    flags=FLAGS)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/backend/application.py", line 126, in standard_tensorboard_wsgi
    plugin_instances = [constructor(context) for constructor in plugins]
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/backend/application.py", line 126, in <listcomp>
    plugin_instances = [constructor(context) for constructor in plugins]
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/plugins/beholder/beholder_plugin.py", line 47, in __init__
    self.most_recent_frame = im_util.get_image_relative_to_script('no-data.png')
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/plugins/beholder/im_util.py", line 254, in get_image_relative_to_script
    return read_image(filename)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/plugins/beholder/im_util.py", line 242, in read_image
    return np.array(decode_png(image_file.read()))
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/plugins/beholder/im_util.py", line 159, in __call__
    self._lazily_initialize()
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/plugins/beholder/im_util.py", line 134, in _lazily_initialize
    self.initialize_graph()
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorboard/plugins/beholder/im_util.py", line 174, in initialize_graph
    self._decode_op = tf.image.decode_png(self._image_placeholder)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 1062, in decode_png
    name=name)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/pi/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

** InvalidArgumentError (see above for traceback): Invalid PNG header, data size 3331
	 [[Node: DecodePng = DecodePng[channels=0, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_0_0)]]**`

@samjabrahams It would be very much appreciated if you could also see this as you are well versed with how tensorflow interacts with the Raspberry Pi, and thank you very much to all reading

**Comment by NMesaC** [comment]
problems arise when compiling tensorflow on raspberry pi 3B when building from wheel file on repoistories instead of from source; changed to build from source and fixed
